---
- name: Rebuild Caddy
  community.docker.docker_compose_v2:
    project_src: "{{ reverse_proxy_dir }}"
    state: present
    build: always

- name: Restart Caddy
  community.docker.docker_compose_v2:
    project_src: "{{ reverse_proxy_dir }}"
    state: restarted
